// MobileGL - MobileGL/MG_Client/ClientTrampoline.cpp
// Copyright (c) 2025-2026 MobileGL-Dev
// Licensed under the GNU Lesser General Public License v3.0:
//   https://www.gnu.org/licenses/gpl-3.0.txt
//   https://www.gnu.org/licenses/lgpl-3.0.txt
// SPDX-License-Identifier: LGPL-3.0-only
// End of Source File Header

#include <Includes.h>

#include "Client.h"
#include "MG_Protocol/generated_opcodes.h"
#include "generated_wire_client.h"
#include "generated_wire_trampoline.h"

// M1 EGL trampoline: the exported EGL entry points that make
// libMobileGL_Client.so loadable as a renderer by LWJGL/FCL. EGL calls use a
// client-side token model (display/context/surface ids) and send typed
// commands to the FullServer. The GL surface is generated by
// scripts/generate_client_trampoline.py into generated_wire_trampoline.cpp and
// only referenced here through eglGetProcAddress.
//
// Caller contract: the first call to any entry point performs
// Client::InitializeFromEnvironment() (MOBILEGL_CS_* environment variables),
// so FCL needs no special bootstrapping.

namespace MobileGL::ClientTrampoline {
    namespace {
        // Token ranges keep display/context/config/surface ids visually
        // distinct; every value is an opaque uint64 that only the client
        // side interprets. All ids stay below 2^32: the control helpers still
        // route session/display/group ids through Uint32 command session_id.
        std::atomic<Uint64> s_nextToken{1};
        std::atomic<Uint64> s_nextDisplay{1'000'000ull};
        std::atomic<Uint64> s_nextGroup{2'000'000ull};
        std::atomic<Uint64> s_nextSession{3'000'000ull};
        std::atomic<Uint64> s_nextSurface{4'000'000ull};
        std::atomic<Uint64> s_nextConfig{5'000'000ull};
        std::atomic<Uint64> s_nextSync{6'000'000ull};

        std::atomic<Bool> s_ready{false};
        Uint64 s_currentDisplay = 0;
        Uint64 s_currentSession = 0;
        Uint64 s_currentContext = 0;
        UnorderedMap<Uint64, Uint64> s_contextSessions;
        UnorderedMap<Uint64, Uint64> s_contextDisplays;

        Uint64 NextToken() {
            return s_nextToken.fetch_add(1);
        }

        Bool EnsureClient() {
            if (s_ready.load()) {
                return true;
            }
            if (!MobileGL::Client::InitializeFromEnvironment()) {
                return false;
            }
            s_ready = true;
            return true;
        }

        Bool Wait(Uint64 token) {
            return MobileGL::Client::WaitResponseForToken(token, 5000);
        }

        Uint64 TokenOf(EGLDisplay display) {
            return static_cast<Uint64>(reinterpret_cast<std::uintptr_t>(display));
        }

        EGLDisplay AsDisplay(Uint64 token) {
            return reinterpret_cast<EGLDisplay>(static_cast<std::uintptr_t>(token));
        }
    } // namespace

    MOBILEGL_EGL_API EGLDisplay eglGetDisplay(NativeDisplayType display) {
        (void)display;
        if (!EnsureClient()) {
            return EGL_NO_DISPLAY;
        }
        const Uint64 id = s_nextDisplay.fetch_add(1);
        const Uint64 token = NextToken();
        if (!MobileGL::Client::SubmitDisplayControl(id, true, token) || !Wait(token)) {
            return EGL_NO_DISPLAY;
        }
        s_currentDisplay = id;
        return AsDisplay(id);
    }

    MOBILEGL_EGL_API EGLDisplay eglGetPlatformDisplay(EGLenum platform, void* native_display,
                                                      const EGLAttrib* attrib_list) {
        (void)platform;
        (void)native_display;
        (void)attrib_list;
        return eglGetDisplay(EGL_DEFAULT_DISPLAY);
    }

    MOBILEGL_EGL_API EGLDisplay eglGetPlatformDisplayEXT(EGLenum platform, void* native_display,
                                                         const EGLint* attrib_list) {
        (void)platform;
        (void)native_display;
        (void)attrib_list;
        return eglGetDisplay(EGL_DEFAULT_DISPLAY);
    }

    MOBILEGL_EGL_API EGLBoolean eglInitialize(EGLDisplay dpy, EGLint* major, EGLint* minor) {
        (void)dpy;
        if (!EnsureClient()) {
            return EGL_FALSE;
        }
        // The display was already initialized server-side by DisplayCreate.
        if (major != nullptr) {
            *major = 1;
        }
        if (minor != nullptr) {
            *minor = 5;
        }
        return EGL_TRUE;
    }

    MOBILEGL_EGL_API EGLBoolean eglTerminate(EGLDisplay dpy) {
        const Uint64 displayId = TokenOf(dpy);
        for (auto it = s_contextDisplays.begin(); it != s_contextDisplays.end();) {
            if (it->second == displayId) {
                const Uint64 session = it->first;
                const Uint64 destroyToken = NextToken();
                MobileGL::Client::SubmitSessionControl(session, false, destroyToken);
                Wait(destroyToken);
                s_contextSessions.erase(session);
                it = s_contextDisplays.erase(it);
            } else {
                ++it;
            }
        }
        const Uint64 displayToken = NextToken();
        MobileGL::Client::SubmitDisplayControl(displayId, false, displayToken);
        Wait(displayToken);
        s_currentDisplay = 0;
        s_currentSession = 0;
        s_currentContext = 0;
        MobileGL::Client::SetCurrentSession(0);
        return EGL_TRUE;
    }

    MOBILEGL_EGL_API EGLBoolean eglBindAPI(EGLenum api) {
        (void)api;
        return EnsureClient() ? EGL_TRUE : EGL_FALSE;
    }

    MOBILEGL_EGL_API EGLBoolean eglChooseConfig(EGLDisplay dpy, const EGLint* attrib_list,
                                                EGLConfig* configs, EGLint config_size,
                                                EGLint* num_config) {
        (void)dpy;
        (void)attrib_list;
        // M1 bootstrap: a single synthetic config token. The real config
        // selection is done by the backend on SessionCreate.
        if (configs != nullptr && config_size > 0) {
            configs[0] = reinterpret_cast<EGLConfig>(
                static_cast<std::uintptr_t>(s_nextConfig.fetch_add(1)));
        }
        if (num_config != nullptr) {
            *num_config = 1;
        }
        return EGL_TRUE;
    }

    MOBILEGL_EGL_API EGLBoolean eglGetConfigs(EGLDisplay dpy, EGLConfig* configs,
                                              EGLint config_size, EGLint* num_config) {
        (void)dpy;
        // M1 bootstrap: the backend chooses the real config on SessionCreate.
        if (configs != nullptr && config_size > 0) {
            configs[0] = reinterpret_cast<EGLConfig>(
                static_cast<std::uintptr_t>(s_nextConfig.fetch_add(1)));
        }
        if (num_config != nullptr) {
            *num_config = 1;
        }
        return EGL_TRUE;
    }

    MOBILEGL_EGL_API EGLBoolean eglGetConfigAttrib(EGLDisplay dpy, EGLConfig config,
                                                   EGLint attribute, EGLint* value) {
        (void)dpy;
        (void)config;
        (void)attribute;
        if (value != nullptr) {
            *value = 0;
        }
        return EGL_TRUE;
    }

    MOBILEGL_EGL_API EGLBoolean eglQuerySurface(EGLDisplay dpy, EGLSurface surface,
                                                EGLint attribute, EGLint* value) {
        (void)dpy;
        (void)surface;
        (void)attribute;
        if (value != nullptr) {
            *value = 0;
        }
        return EGL_TRUE;
    }

    MOBILEGL_EGL_API EGLBoolean eglReleaseThread(void) {
        return EGL_TRUE;
    }

    MOBILEGL_EGL_API EGLContext eglCreateContext(EGLDisplay dpy, EGLConfig config,
                                                 EGLContext shareCtx,
                                                 const EGLint* attrib_list) {
        (void)config;
        (void)shareCtx;
        (void)attrib_list;
        if (!EnsureClient()) {
            return EGL_NO_CONTEXT;
        }
        const Uint64 displayId = TokenOf(dpy) != 0 ? TokenOf(dpy) : s_currentDisplay;
        const Uint64 sessionId = s_nextSession.fetch_add(1);
        const Uint64 groupId = s_nextGroup.fetch_add(1);

        Uint64 token = NextToken();
        if (!MobileGL::Client::SubmitSharedGroupControl(groupId, true, token) || !Wait(token)) {
            return EGL_NO_CONTEXT;
        }
        token = NextToken();
        if (!MobileGL::Client::SubmitSessionControl(sessionId, true, token) || !Wait(token)) {
            return EGL_NO_CONTEXT;
        }

        s_currentSession = sessionId;
        s_currentContext = sessionId;
        s_contextSessions[sessionId] = sessionId;
        s_contextDisplays[sessionId] = displayId;
        MobileGL::Client::SetCurrentSession(sessionId);
        return reinterpret_cast<EGLContext>(static_cast<std::uintptr_t>(sessionId));
    }

    MOBILEGL_EGL_API EGLBoolean eglDestroyContext(EGLDisplay dpy, EGLContext ctx) {
        (void)dpy;
        const Uint64 sessionId = static_cast<Uint64>(
            reinterpret_cast<std::uintptr_t>(ctx));
        const auto it = s_contextSessions.find(sessionId);
        if (it == s_contextSessions.end()) {
            return EGL_FALSE;
        }
        const Uint64 token = NextToken();
        MobileGL::Client::SubmitSessionControl(sessionId, false, token);
        Wait(token);
        s_contextSessions.erase(it);
        s_contextDisplays.erase(sessionId);
        if (s_currentSession == sessionId) {
            s_currentSession = 0;
            s_currentContext = 0;
            MobileGL::Client::SetCurrentSession(0);
        }
        return EGL_TRUE;
    }

    MOBILEGL_EGL_API EGLSurface eglCreateWindowSurface(EGLDisplay dpy, EGLConfig config,
                                                       NativeWindowType window,
                                                       const EGLint* attrib_list) {
        (void)config;
        (void)attrib_list;
        if (!EnsureClient()) {
            return EGL_NO_SURFACE;
        }
        const Uint64 displayId = TokenOf(dpy) != 0 ? TokenOf(dpy) : s_currentDisplay;
        const Uint64 surfaceId = s_nextSurface.fetch_add(1);
        const Uint64 nativeWindow =
            static_cast<Uint64>(reinterpret_cast<std::uintptr_t>(window));
        const Uint64 token = NextToken();
        if (!MobileGL::Client::SendEglCreateWindowSurface(displayId, surfaceId,
                                                          nativeWindow, token)) {
            return EGL_NO_SURFACE;
        }
        return reinterpret_cast<EGLSurface>(static_cast<std::uintptr_t>(surfaceId));
    }

    MOBILEGL_EGL_API EGLSurface eglCreatePlatformWindowSurface(EGLDisplay dpy, EGLConfig config,
                                                               void* native_window,
                                                               const EGLAttrib* attrib_list) {
        (void)config;
        (void)attrib_list;
        if (!EnsureClient()) {
            return EGL_NO_SURFACE;
        }
        const Uint64 displayId = TokenOf(dpy) != 0 ? TokenOf(dpy) : s_currentDisplay;
        const Uint64 surfaceId = s_nextSurface.fetch_add(1);
        const Uint64 nativeWindow =
            static_cast<Uint64>(reinterpret_cast<std::uintptr_t>(native_window));
        const Uint64 token = NextToken();
        if (!MobileGL::Client::SendEglCreateWindowSurface(displayId, surfaceId,
                                                          nativeWindow, token)) {
            return EGL_NO_SURFACE;
        }
        return reinterpret_cast<EGLSurface>(static_cast<std::uintptr_t>(surfaceId));
    }

    MOBILEGL_EGL_API EGLSurface eglCreatePbufferSurface(EGLDisplay dpy, EGLConfig config,
                                                        const EGLint* attrib_list) {
        (void)config;
        (void)attrib_list;
        if (!EnsureClient()) {
            return EGL_NO_SURFACE;
        }
        const Uint64 displayId = TokenOf(dpy) != 0 ? TokenOf(dpy) : s_currentDisplay;
        const Uint64 surfaceId = s_nextSurface.fetch_add(1);
        const Uint64 token = NextToken();
        if (!MobileGL::Client::SendEglCreatePbufferSurface(displayId, surfaceId, 1, 1, token)) {
            return EGL_NO_SURFACE;
        }
        return reinterpret_cast<EGLSurface>(static_cast<std::uintptr_t>(surfaceId));
    }

    MOBILEGL_EGL_API EGLBoolean eglDestroySurface(EGLDisplay dpy, EGLSurface surface) {
        const Uint64 displayId = TokenOf(dpy) != 0 ? TokenOf(dpy) : s_currentDisplay;
        const Uint64 surfaceId = static_cast<Uint64>(
            reinterpret_cast<std::uintptr_t>(surface));
        const Uint64 token = NextToken();
        return MobileGL::Client::SendEglDestroySurface(displayId, surfaceId, token);
    }

    MOBILEGL_EGL_API EGLBoolean eglMakeCurrent(EGLDisplay dpy, EGLSurface draw,
                                               EGLSurface read, EGLContext ctx) {
        (void)dpy;
        if (!EnsureClient()) {
            return EGL_FALSE;
        }
        const Uint64 sessionId = s_currentSession != 0
            ? s_currentSession
            : static_cast<Uint64>(reinterpret_cast<std::uintptr_t>(ctx));
        const Uint64 drawId = static_cast<Uint64>(reinterpret_cast<std::uintptr_t>(draw));
        const Uint64 readId = static_cast<Uint64>(reinterpret_cast<std::uintptr_t>(read));
        const Uint64 token = NextToken();
        if (!MobileGL::Client::SendEglMakeCurrent(sessionId, drawId, readId, token)) {
            return EGL_FALSE;
        }
        if (draw == EGL_NO_SURFACE && read == EGL_NO_SURFACE && ctx == EGL_NO_CONTEXT) {
            s_currentSession = 0;
            s_currentContext = 0;
            MobileGL::Client::SetCurrentSession(0);
        } else {
            s_currentContext = sessionId;
            MobileGL::Client::SetCurrentSession(sessionId);
        }
        return EGL_TRUE;
    }

    MOBILEGL_EGL_API EGLBoolean eglSwapBuffers(EGLDisplay dpy, EGLSurface draw) {
        (void)dpy;
        if (!EnsureClient()) {
            return EGL_FALSE;
        }
        const Uint64 drawId = static_cast<Uint64>(reinterpret_cast<std::uintptr_t>(draw));
        const Uint64 token = NextToken();
        return MobileGL::Client::SendSwapBuffers(s_currentSession, drawId, token);
    }

    MOBILEGL_EGL_API EGLBoolean eglSwapInterval(EGLDisplay dpy, EGLint interval) {
        if (!EnsureClient()) {
            return EGL_FALSE;
        }
        const Uint64 displayId = TokenOf(dpy) != 0 ? TokenOf(dpy) : s_currentDisplay;
        const Uint64 token = NextToken();
        return MobileGL::Client::SendEglSetSwapInterval(displayId, interval, token);
    }

    MOBILEGL_EGL_API EGLSync eglCreateSync(EGLDisplay dpy, EGLenum type,
                                           const EGLAttrib* attrib_list) {
        (void)dpy;
        (void)type;
        (void)attrib_list;
        // Bootstrap: a synthetic sync token; real sync wire ops land with the
        // typed EGL sync channel.
        return reinterpret_cast<EGLSync>(static_cast<std::uintptr_t>(s_nextSync.fetch_add(1)));
    }

    MOBILEGL_EGL_API EGLBoolean eglDestroySync(EGLDisplay dpy, EGLSync sync) {
        (void)dpy;
        (void)sync;
        return EGL_TRUE;
    }

    MOBILEGL_EGL_API EGLint eglClientWaitSync(EGLDisplay dpy, EGLSync sync, EGLint flags,
                                              EGLTime timeout) {
        (void)dpy;
        (void)sync;
        (void)flags;
        (void)timeout;
        return EGL_CONDITION_SATISFIED;
    }

    MOBILEGL_EGL_API EGLBoolean eglGetSyncAttrib(EGLDisplay dpy, EGLSync sync,
                                                 EGLint attribute, EGLAttrib* value) {
        (void)dpy;
        (void)sync;
        (void)attribute;
        if (value != nullptr) {
            *value = 0;
        }
        return EGL_TRUE;
    }

    MOBILEGL_EGL_API EGLBoolean eglWaitSync(EGLDisplay dpy, EGLSync sync, EGLint flags) {
        (void)dpy;
        (void)sync;
        (void)flags;
        return EGL_TRUE;
    }

    MOBILEGL_EGL_API EGLint eglGetError(void) {
        return EGL_SUCCESS;
    }

    MOBILEGL_EGL_API char const* eglQueryString(EGLDisplay dpy, EGLint name) {
        (void)dpy;
        switch (name) {
            case EGL_VENDOR:
                return "MobileGL";
            case EGL_VERSION:
                return "1.5 (MobileGL Client)";
            default:
                return nullptr;
        }
    }

    MOBILEGL_EGL_API EGLContext eglGetCurrentContext(void) {
        return reinterpret_cast<EGLContext>(static_cast<std::uintptr_t>(s_currentContext));
    }

    MOBILEGL_EGL_API EGLDisplay eglGetCurrentDisplay(void) {
        return AsDisplay(s_currentDisplay);
    }

    MOBILEGL_EGL_API EGLSurface eglGetCurrentSurface(EGLint readdraw) {
        (void)readdraw;
        return EGL_NO_SURFACE;
    }

    // Hand-written GL entries whose wire payload tables do not exist yet
    // (no payload table in generated_dispatch.h). The remaining GL surface is
    // generated by generate_client_trampoline.py.
    MOBILEGL_GL_API void glReadPixels(GLint x, GLint y, GLsizei width, GLsizei height,
                                      GLenum format, GLenum type, void* pixels) {
        if (!EnsureClient() || s_currentSession == 0 || pixels == nullptr) {
            return;
        }
        const Uint64 size = static_cast<Uint64>(width) * static_cast<Uint64>(height) * 4ull;
        MobileGL::Client::SendReadPixels(s_currentSession, x, y, width, height,
                                         static_cast<uint32_t>(format),
                                         static_cast<uint32_t>(type), pixels, size, NextToken());
    }

    MOBILEGL_GL_API void glFlush(void) {
        // Client-side no-op until the wire sync-point protocol lands.
    }

    MOBILEGL_GL_API void glFinish(void) {
        // Client-side no-op until the wire sync-point protocol lands.
    }

    MOBILEGL_GL_API GLenum glGetError(void) {
        return GL_NO_ERROR;
    }

    MOBILEGL_GL_API void glShaderSource(GLuint shader, GLsizei count,
                                        const GLchar* const* string, const GLint* length) {
        if (!EnsureClient() || s_currentSession == 0 || count <= 0 || string == nullptr) {
            return;
        }
        (void)length; // bootstrap path assumes NUL-terminated sources.
        SizeT total = 0;
        for (GLsizei i = 0; i < count; ++i) {
            total += (string[i] != nullptr ? std::strlen(string[i]) : 0) + 1;
        }
        if (total == 0) {
            return;
        }
        MobileGLShmHandle shm{};
        if (!MobileGL::Client::AllocateShm(total, &shm) || shm.mappedAddress == nullptr) {
            return;
        }
        char* dst = static_cast<char*>(shm.mappedAddress);
        for (GLsizei i = 0; i < count; ++i) {
            const SizeT len = string[i] != nullptr ? std::strlen(string[i]) : 0;
            if (len > 0) {
                memcpy(dst, string[i], len);
            }
            dst[len] = '\0';
            dst += len + 1;
        }
        const Uint64 token = NextToken();
        flatbuffers::FlatBufferBuilder builder;
        const auto region = MobileGL::Protocol::WireFull::CreateShmRegion(builder, 0, total);
        const auto payload = MobileGL::Protocol::WireFull::CreateGenShaderSource(
            builder, shader, count, region, 0);
        builder.Finish(payload);
        MobileGL::Client::SendWirePayload(
            s_currentSession,
            static_cast<uint32_t>(MobileGL::Protocol::MobileGLOpcode::glShaderSource),
            token, builder.GetBufferPointer(), static_cast<Uint32>(builder.GetSize()), &shm);
        MobileGL::Client::ReleaseShm(&shm);
    }

    // Bootstrap pixel-size helper: exact matches for common upload formats;
    // the fallback of 4 bytes/pixel keeps GL_RGBA/GL_UNSIGNED_BYTE correct.
    static SizeT TexBytesPerPixel(GLenum format, GLenum type) {
        if (type == 0x1401) { // GL_UNSIGNED_BYTE
            switch (format) {
                case 0x1903: return 1; // GL_RED
                case 0x8227: return 1; // GL_RG
                case 0x1907: return 3; // GL_RGB
                case 0x1908: return 4; // GL_RGBA
                case 0x1909: return 1; // GL_LUMINANCE
                case 0x190A: return 2; // GL_LUMINANCE_ALPHA
                case 0x80E0: return 3; // GL_BGR
                case 0x80E1: return 4; // GL_BGRA
                default: return 4;
            }
        }
        if (type == 0x1403) { // GL_UNSIGNED_SHORT_5_6_5 / 4_4_4_4 / 5_5_5_1
            return 2;
        }
        if (type == 0x1405) { // GL_UNSIGNED_INT
            return 4;
        }
        return 4;
    }

    MOBILEGL_GL_API void glTexImage2D(GLenum target, GLint level, GLint internalformat,
                                      GLsizei width, GLsizei height, GLint border,
                                      GLenum format, GLenum type, const void* pixels) {
        if (!EnsureClient() || s_currentSession == 0) {
            return;
        }
        if (pixels != nullptr && width > 0 && height > 0) {
            const Uint64 dataSize = static_cast<Uint64>(width) *
                static_cast<Uint64>(height) * TexBytesPerPixel(format, type);
            MobileGLShmHandle shm{};
            if (MobileGL::Client::AllocateShm(dataSize, &shm) && shm.mappedAddress != nullptr) {
                shm.size = dataSize;
                memcpy(shm.mappedAddress, pixels, static_cast<SizeT>(dataSize));
                const Uint64 token = NextToken();
                MobileGL::Client::Wire::SendGlTexImage2D(
                    s_currentSession, target, level, internalformat, width, height, border,
                    format, type, token, &shm);
                MobileGL::Client::ReleaseShm(&shm);
                return;
            }
        }
        // Null pixels: rely on the generic path with no shm.
        const Uint64 token = NextToken();
        MobileGL::Client::Wire::SendGlTexImage2D(
            s_currentSession, target, level, internalformat, width, height, border,
            format, type, token, nullptr);
    }

    MOBILEGL_GL_API void glTexSubImage2D(GLenum target, GLint level, GLint xoffset,
                                         GLint yoffset, GLsizei width, GLsizei height,
                                         GLenum format, GLenum type, const void* pixels) {
        if (!EnsureClient() || s_currentSession == 0) {
            return;
        }
        if (pixels != nullptr && width > 0 && height > 0) {
            const Uint64 dataSize = static_cast<Uint64>(width) *
                static_cast<Uint64>(height) * TexBytesPerPixel(format, type);
            MobileGLShmHandle shm{};
            if (MobileGL::Client::AllocateShm(dataSize, &shm) && shm.mappedAddress != nullptr) {
                shm.size = dataSize;
                memcpy(shm.mappedAddress, pixels, static_cast<SizeT>(dataSize));
                const Uint64 token = NextToken();
                MobileGL::Client::Wire::SendGlTexSubImage2D(
                    s_currentSession, target, level, xoffset, yoffset, width, height,
                    format, type, token, &shm);
                MobileGL::Client::ReleaseShm(&shm);
                return;
            }
        }
        const Uint64 token = NextToken();
        MobileGL::Client::Wire::SendGlTexSubImage2D(
            s_currentSession, target, level, xoffset, yoffset, width, height,
            format, type, token, nullptr);
    }

    MOBILEGL_GL_API void glTexImage3D(GLenum target, GLint level, GLint internalformat,
                                      GLsizei width, GLsizei height, GLsizei depth,
                                      GLint border, GLenum format, GLenum type,
                                      const void* pixels) {
        if (!EnsureClient() || s_currentSession == 0) {
            return;
        }
        if (pixels != nullptr && width > 0 && height > 0 && depth > 0) {
            const Uint64 dataSize = static_cast<Uint64>(width) *
                static_cast<Uint64>(height) * static_cast<Uint64>(depth) *
                TexBytesPerPixel(format, type);
            MobileGLShmHandle shm{};
            if (MobileGL::Client::AllocateShm(dataSize, &shm) && shm.mappedAddress != nullptr) {
                shm.size = dataSize;
                memcpy(shm.mappedAddress, pixels, static_cast<SizeT>(dataSize));
                const Uint64 token = NextToken();
                MobileGL::Client::Wire::SendGlTexImage3D(
                    s_currentSession, target, level, internalformat, width, height, depth,
                    border, format, type, token, &shm);
                MobileGL::Client::ReleaseShm(&shm);
                return;
            }
        }
        const Uint64 token = NextToken();
        MobileGL::Client::Wire::SendGlTexImage3D(
            s_currentSession, target, level, internalformat, width, height, depth,
            border, format, type, token, nullptr);
    }

    // Shared decoder for the [length,size,type,name] blob returned by
    // glGetActiveAttrib/glGetActiveUniform.
    static void DecodeActiveVariable(const Vector<Uint8>& bytes, GLsizei* length,
                                     GLint* size, GLenum* type, GLchar* name,
                                     GLsizei bufSize) {
        if (bytes.size() < 12) {
            return;
        }
        const auto rdU32 = [&bytes](SizeT offset) -> Uint32 {
            return static_cast<Uint32>(bytes[offset]) |
                   (static_cast<Uint32>(bytes[offset + 1]) << 8) |
                   (static_cast<Uint32>(bytes[offset + 2]) << 16) |
                   (static_cast<Uint32>(bytes[offset + 3]) << 24);
        };
        if (length != nullptr) {
            *length = static_cast<GLsizei>(rdU32(0));
        }
        if (size != nullptr) {
            *size = static_cast<GLint>(rdU32(4));
        }
        if (type != nullptr) {
            *type = static_cast<GLenum>(rdU32(8));
        }
        if (name != nullptr && bufSize > 0) {
            const SizeT available = bytes.size() - 12;
            const SizeT copy = available < static_cast<SizeT>(bufSize - 1)
                ? available
                : static_cast<SizeT>(bufSize - 1);
            memcpy(name, bytes.data() + 12, copy);
            name[copy] = '\0';
        }
    }

    MOBILEGL_GL_API void glGetActiveAttrib(GLuint program, GLuint index, GLsizei bufSize,
                                           GLsizei* length, GLint* size, GLenum* type,
                                           GLchar* name) {
        if (!EnsureClient() || s_currentSession == 0) {
            return;
        }
        const Uint64 token = NextToken();
        if (!MobileGL::Client::SendGetActiveAttrib(
                s_currentSession, program, index, static_cast<uint32_t>(bufSize), token)) {
            return;
        }
        DecodeActiveVariable(MobileGL::Client::GetLastResponseBytes(),
                             length, size, type, name, bufSize);
    }

    MOBILEGL_GL_API void glGetActiveUniform(GLuint program, GLuint index, GLsizei bufSize,
                                            GLsizei* length, GLint* size, GLenum* type,
                                            GLchar* name) {
        if (!EnsureClient() || s_currentSession == 0) {
            return;
        }
        const Uint64 token = NextToken();
        if (!MobileGL::Client::SendGetActiveUniform(
                s_currentSession, program, index, static_cast<uint32_t>(bufSize), token)) {
            return;
        }
        DecodeActiveVariable(MobileGL::Client::GetLastResponseBytes(),
                             length, size, type, name, bufSize);
    }

    namespace {
        void* LookupProcAddress(const char* name) {
            if (name == nullptr) {
                return nullptr;
            }
#define MOBILEGL_CS_PROCP(function)                                                                                      \
        if (std::strcmp(name, #function) == 0) {                                                                         \
            return reinterpret_cast<void*>(&function);                                                                   \
        }
            MOBILEGL_CS_PROCP(eglGetDisplay);
            MOBILEGL_CS_PROCP(eglGetPlatformDisplay);
            MOBILEGL_CS_PROCP(eglGetPlatformDisplayEXT);
            MOBILEGL_CS_PROCP(eglInitialize);
            MOBILEGL_CS_PROCP(eglTerminate);
            MOBILEGL_CS_PROCP(eglBindAPI);
            MOBILEGL_CS_PROCP(eglChooseConfig);
            MOBILEGL_CS_PROCP(eglGetConfigs);
            MOBILEGL_CS_PROCP(eglGetConfigAttrib);
            MOBILEGL_CS_PROCP(eglQuerySurface);
            MOBILEGL_CS_PROCP(eglReleaseThread);
            MOBILEGL_CS_PROCP(eglCreateContext);
            MOBILEGL_CS_PROCP(eglDestroyContext);
            MOBILEGL_CS_PROCP(eglCreateWindowSurface);
            MOBILEGL_CS_PROCP(eglCreatePlatformWindowSurface);
            MOBILEGL_CS_PROCP(eglCreatePbufferSurface);
            MOBILEGL_CS_PROCP(eglDestroySurface);
            MOBILEGL_CS_PROCP(eglMakeCurrent);
            MOBILEGL_CS_PROCP(eglSwapBuffers);
            MOBILEGL_CS_PROCP(eglSwapInterval);
            MOBILEGL_CS_PROCP(eglCreateSync);
            MOBILEGL_CS_PROCP(eglDestroySync);
            MOBILEGL_CS_PROCP(eglClientWaitSync);
            MOBILEGL_CS_PROCP(eglGetSyncAttrib);
            MOBILEGL_CS_PROCP(eglWaitSync);
            MOBILEGL_CS_PROCP(eglGetError);
            MOBILEGL_CS_PROCP(eglQueryString);
            MOBILEGL_CS_PROCP(eglGetCurrentContext);
            MOBILEGL_CS_PROCP(eglGetCurrentDisplay);
            MOBILEGL_CS_PROCP(eglGetCurrentSurface);
            // GL entry points below are defined by generated_wire_trampoline.cpp
            // (except the hand-written ones listed here).
            MOBILEGL_CS_PROCP(glClearColor);
            MOBILEGL_CS_PROCP(glClear);
            MOBILEGL_CS_PROCP(glViewport);
            MOBILEGL_CS_PROCP(glReadPixels);
            MOBILEGL_CS_PROCP(glDrawArrays);
            MOBILEGL_CS_PROCP(glFlush);
            MOBILEGL_CS_PROCP(glFinish);
            MOBILEGL_CS_PROCP(glGetError);
            MOBILEGL_CS_PROCP(glGetString);
            MOBILEGL_CS_PROCP(glGetStringi);
            MOBILEGL_CS_PROCP(glShaderSource);
            MOBILEGL_CS_PROCP(glGetActiveAttrib);
            MOBILEGL_CS_PROCP(glGetActiveUniform);
            MOBILEGL_CS_PROCP(glTexImage2D);
            MOBILEGL_CS_PROCP(glTexImage3D);
            MOBILEGL_CS_PROCP(glTexSubImage2D);
#undef MOBILEGL_CS_PROCP
            // Every generated trampoline (the exported gl* surface) resolves
            // through the generated address table - direct &glXxx references,
            // mirroring monolith MobileGL::MG_Impl::GetProcAddress semantics
            // (no dlsym fallback).
            return MobileGL::ClientTrampoline::Gen::LookupGeneratedProc(name);
        }
    } // namespace

    MOBILEGL_EGL_API __eglMustCastToProperFunctionPointerType eglGetProcAddress(const char* name) {
        return reinterpret_cast<__eglMustCastToProperFunctionPointerType>(LookupProcAddress(name));
    }

    // GLX loader entry points: LWJGL's desktop-OpenGL function provider queries
    // glXGetProcAddress(ARB) (X11/GLX path) in addition to eglGetProcAddress.
    // Both share the client symbol table. The return type is GLXFuncPtr
    // (void (*)(void)) without pulling in <GL/glx.h> (no X11 on Android).
    using GLXFuncPtr = void (*)(void);

    MOBILEGL_GLX_API GLXFuncPtr glXGetProcAddress(const GLubyte* name) {
        return reinterpret_cast<GLXFuncPtr>(LookupProcAddress(
            name == nullptr ? nullptr : reinterpret_cast<const char*>(name)));
    }

    MOBILEGL_GLX_API GLXFuncPtr glXGetProcAddressARB(const GLubyte* name) {
        return reinterpret_cast<GLXFuncPtr>(LookupProcAddress(
            name == nullptr ? nullptr : reinterpret_cast<const char*>(name)));
    }
} // namespace MobileGL::ClientTrampoline

// End of File
