#!/usr/bin/env python3
"""
MobileGL - scripts/extract_api_manifest.py
Copyright (c) 2025-2026 MobileGL-Dev
Licensed under the GNU Lesser General Public License v3.0:
  https://www.gnu.org/licenses/gpl-3.0.txt
  https://www.gnu.org/licenses/lgpl-3.0.txt
SPDX-License-Identifier: LGPL-3.0-only

Extract the GL/EGL/GLX API manifest from the existing implementation sources.
This is Phase 4 codegen input: each line is one exported API entry.

Output format (tab-separated):
    category<TAB>name<TAB>source
where category is one of GL / EGL / GLX / CGL / WGL.
"""
from __future__ import annotations

import re
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]

# One regex that captures any project prefix plus the API suffix name.
API_NAME_RE = re.compile(r"\b(gl|egl|glX|CGL|wgl)([A-Za-z0-9_]+)\b")


def scan_file(path: Path) -> list[tuple[str, str, str]]:
    entries: set[tuple[str, str, str]] = set()
    for line_no, line in enumerate(path.read_text(encoding="utf-8", errors="replace").splitlines(), start=1):
        for match in API_NAME_RE.finditer(line):
            prefix = match.group(1)
            name = prefix + match.group(2)
            # Keep the source spelling exact; the category is derived from prefix.
            if prefix == "gl":
                category = "GL"
            elif prefix == "egl":
                category = "EGL"
            elif prefix == "glX":
                category = "GLX"
            elif prefix == "CGL":
                category = "CGL"
            else:
                category = "WGL"
            entries.add((category, name, f"{path.relative_to(REPO_ROOT)}:{line_no}"))
    return sorted(entries)


def main() -> int:
    inputs = [
        REPO_ROOT / "MobileGL/MG_Impl/GLImpl/Exporting/Definitions.cpp",
        REPO_ROOT / "MobileGL/MG_Impl/EGLImpl/Exporting/Definitions.cpp",
        REPO_ROOT / "MobileGL/MG_Impl/GLXImpl/Exporting/Definitions.cpp",
        REPO_ROOT / "MobileGL/MG_Impl/GetProcAddress.cpp",
    ]

    entries: set[tuple[str, str, str]] = set()
    for path in inputs:
        if path.exists():
            entries.update(scan_file(path))

    output_path = REPO_ROOT / "MobileGL/MG_Protocol/api_manifest.txt"
    lines = [
        "# MobileGL API manifest (generated by scripts/extract_api_manifest.py)",
        "# category<TAB>name<TAB>source",
    ]
    for category, name, source in sorted(entries):
        lines.append(f"{category}\t{name}\t{source}")
    output_path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"Wrote {len(lines) - 2} entries to {output_path.relative_to(REPO_ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
