#!/usr/bin/env python3
"""
MobileGL - scripts/generate_wire_full_fbs.py
Copyright (c) 2025-2026 MobileGL-Dev
Licensed under the GNU Lesser General Public License v3.0:
  https://www.gnu.org/licenses/gpl-3.0.txt
  https://www.gnu.org/licenses/lgpl-3.0.txt
SPDX-License-Identifier: LGPL-3.0-only
End of Source File Header

Generate MobileGL/MG_Protocol/wire_full.fbs from
MobileGL/MG_Protocol/protocol_generated.fbs: every generated Gl* payload table
is renamed to Gen* under namespace MobileGL.Protocol.WireFull, and a generic
Command/Message/Response envelope is appended. The server decodes the payload
bytes carried by Command.payload_bytes with WireFull::GetGen*; typed legacy
wire.fbs remains untouched for the existing Client API surface.
"""
from __future__ import annotations

import re
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
GENERATED = REPO_ROOT / "MobileGL/MG_Protocol/protocol_generated.fbs"
OUTPUT = REPO_ROOT / "MobileGL/MG_Protocol/wire_full.fbs"

TABLE_RE = re.compile(r"^\s*table\s+(\w+)\s*\{", re.MULTILINE)


def collect_tables(text: str) -> dict[str, str]:
    tables: dict[str, str] = {}
    pos = 0
    while True:
        match = TABLE_RE.search(text, pos)
        if match is None:
            break
        name = match.group(1)
        start = match.start()
        brace_index = match.end() - 1
        depth = 0
        cursor = brace_index
        while cursor < len(text):
            ch = text[cursor]
            if ch == "{":
                depth += 1
            elif ch == "}":
                depth -= 1
                if depth == 0:
                    break
            cursor += 1
        tables[name] = text[start : cursor + 1]
        pos = cursor + 1
    return tables


def main() -> int:
    if not GENERATED.exists():
        print(f"missing {GENERATED}", file=__import__("sys").stderr)
        return 1

    generated = GENERATED.read_text(encoding="utf-8")
    tables = collect_tables(generated)

    lines: list[str] = []
    lines.append(
        "// MobileGL - MobileGL/MG_Protocol/wire_full.fbs\n"
        "// Copyright (c) 2025-2026 MobileGL-Dev\n"
        "// Licensed under the GNU Lesser General Public License v3.0:\n"
        "// SPDX-License-Identifier: LGPL-3.0-only\n"
        "// End of Source File Header\n\n"
        "// GENERATED by scripts/generate_wire_full_fbs.py from\n"
        "// protocol_generated.fbs. Do not edit by hand.\n\n"
        "namespace MobileGL.Protocol.WireFull;\n\n"
        "table ShmRegion {\n"
        "    offset: ulong;\n"
        "    size: ulong;\n"
        "}\n\n"
    )

    seen: set[str] = set()
    for name, block in tables.items():
        if not (name.startswith("Gl") or name.startswith("Egl")):
            continue
        if name.startswith("Egl"):
            # EGL payload tables use GenEgl* so glClientWaitSync and
            # eglClientWaitSync never collide after renaming.
            new_name = "GenEgl" + name[3:]
            renamed = re.sub(r"^\s*table\s+Egl", "table GenEgl", block, count=1)
        else:
            new_name = "Gen" + name[2:]
            renamed = re.sub(r"^\s*table\s+Gl", "table Gen", block, count=1)
        if new_name in seen:
            continue
        seen.add(new_name)
        # Replace the leading table name inside the block only.
        lines.append(renamed)
        lines.append("\n")

    lines.append(
        "table Command {\n"
        "    opcode: uint;\n"
        "    session_id: ulong;\n"
        "    token: ulong;\n"
        "    payload_bytes: [ubyte];\n"
        "    out_capacity: uint;\n"
        "}\n\n"
        "table Message {\n"
        "    command: Command;\n"
        "    shm_count: uint;\n"
        "}\n\n"
        "table Response {\n"
        "    status: uint;\n"
        "    token: ulong;\n"
        "    session_id: ulong;\n"
        "    data_byte: uint;\n"
        "    sync: ulong;\n"
        "    string_value: string;\n"
        "    ret_shm_count: uint;\n"
        "    query_ns: ulong;\n"
        "    ret_i64: long;\n"
        "    ret_bytes: [ubyte];\n"
        "}\n\n"
        "root_type Message;\n"
    )

    OUTPUT.write_text("".join(lines), encoding="utf-8")
    print(f"Wrote {len(seen)} Gen* payload tables to {OUTPUT.relative_to(REPO_ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
