#!/usr/bin/env python3
"""
MobileGL - scripts/generate_dispatch_table.py
Copyright (c) 2025-2026 MobileGL-Dev
Licensed under the GNU Lesser General Public License v3.0:
  https://www.gnu.org/licenses/gpl-3.0.txt
  https://www.gnu.org/licenses/lgpl-3.0.txt
SPDX-License-Identifier: LGPL-3.0-only

Generate MobileGL/MG_Protocol/generated_dispatch.h: opcode -> API name ->
payload table name metadata for the runtime trampoline layer.
"""
from __future__ import annotations

import re
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
MANIFEST = REPO_ROOT / "MobileGL/MG_Protocol/api_manifest.txt"
OPCODE_H = REPO_ROOT / "MobileGL/MG_Protocol/generated_opcodes.h"
GENERATED_FBS = REPO_ROOT / "MobileGL/MG_Protocol/protocol_generated.fbs"
OUTPUT = REPO_ROOT / "MobileGL/MG_Protocol/generated_dispatch.h"

TABLE_RE = re.compile(r"^\s*table\s+(\w+)\s*\{", re.MULTILINE)


def main() -> int:
    if not all(path.exists() for path in (MANIFEST, OPCODE_H, GENERATED_FBS)):
        print("missing input", file=__import__("sys").stderr)
        return 1

    # opcode number by GL name from generated_opcodes.h
    opcode_by_name: dict[str, int] = {}
    for line in OPCODE_H.read_text(encoding="utf-8").splitlines():
        match = re.match(r"\s*(\w+)\s*=\s*(\d+),", line)
        if match:
            opcode_by_name[match.group(1)] = int(match.group(2))

    # payload table names from protocol_generated.fbs
    table_names = set(TABLE_RE.findall(GENERATED_FBS.read_text(encoding="utf-8")))

    # API names from manifest
    apis: list[str] = []
    for line in MANIFEST.read_text(encoding="utf-8").splitlines():
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        parts = line.split("\t")
        if len(parts) < 2:
            continue
        name = parts[1].strip()
        if not name.startswith(("gl", "egl")):
            continue
        apis.append(name)
    apis = sorted(set(apis))

    entries: list[tuple[int, str, str]] = []
    for api in apis:
        opcode = opcode_by_name.get(api)
        if opcode is None:
            continue
        table = api[0].upper() + api[1:]
        entries.append((opcode, api, table if table in table_names else ""))

    entries.sort(key=lambda item: item[0])

    lines = []
    for opcode, api, table in entries:
        lines.append(f'    {{{opcode}u, "{api}", "{table}"}},')
    header = (
        "// MobileGL - MobileGL/MG_Protocol/generated_dispatch.h\n"
        "// Copyright (c) 2025-2026 MobileGL-Dev\n"
        "// Licensed under the GNU Lesser General Public License v3.0:\n"
        "//   https://www.gnu.org/licenses/gpl-3.0.txt\n"
        "//   https://www.gnu.org/licenses/lgpl-3.0.txt\n"
        "// SPDX-License-Identifier: LGPL-3.0-only\n"
        "// End of Source File Header\n\n"
        "#pragma once\n\n"
        "#include <cstdint>\n\n"
        "// GENERATED by scripts/generate_dispatch_table.py\n\n"
        "namespace MobileGL::Protocol {\n\n"
        "struct MobileGLDispatchEntry {\n"
        "    uint32_t opcode;\n"
        "    const char* api;\n"
        "    const char* payloadTable;\n"
        "};\n\n"
        f"inline constexpr uint32_t kMobileGLDispatchCount = {len(entries)}u;\n\n"
        "inline constexpr MobileGLDispatchEntry kMobileGLDispatch[kMobileGLDispatchCount] = {\n"
        + "\n".join(lines) +
        "\n};\n\n"
        "inline const char* MobileGLDispatchApi(uint32_t opcode) {\n"
        "    for (uint32_t i = 0; i < kMobileGLDispatchCount; ++i) {\n"
        "        if (kMobileGLDispatch[i].opcode == opcode) return kMobileGLDispatch[i].api;\n"
        "    }\n"
        "    return \"?\";\n"
        "}\n\n"
        "} // namespace MobileGL::Protocol\n\n"
        "// End of File\n"
    )
    OUTPUT.write_text(header, encoding="utf-8")
    print(f"Wrote {len(entries)} dispatch entries to {OUTPUT.relative_to(REPO_ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
