#!/usr/bin/env python3
"""
MobileGL - scripts/generate_opcode_table.py
Copyright (c) 2025-2026 MobileGL-Dev
Licensed under the GNU Lesser General Public License v3.0:
  https://www.gnu.org/licenses/gpl-3.0.txt
  https://www.gnu.org/licenses/lgpl-3.0.txt
SPDX-License-Identifier: LGPL-3.0-only

Generate MobileGL/MG_Protocol/generated_opcodes.h from api_manifest.txt.

The generated header provides:
  - enum class MobileGLOpcode : uint32_t (stable, never-reordered; name = 1-based index)
  - constexpr kMobileGLOpcodeCount
  - inline kMobileGLOpcodeNames[] name lookup
"""
from __future__ import annotations

import re
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
MANIFEST = REPO_ROOT / "MobileGL/MG_Protocol/api_manifest.txt"
OUTPUT = REPO_ROOT / "MobileGL/MG_Protocol/generated_opcodes.h"

# Only GL and EGL APIs get an opcode; GLX/CGL/WGL stay out of the C/S protocol
# for now (they are desktop bindings that do not cross the server boundary).
ALLOWED_PREFIXES = ("gl", "egl")


def sanitize_name(name: str) -> str:
    return re.sub(r"[^A-Za-z0-9_]", "_", name)


def main() -> int:
    if not MANIFEST.exists():
        print(f"missing {MANIFEST}", file=__import__("sys").stderr)
        return 1

    entries: list[tuple[str, str]] = set()  # type: ignore[assignment]
    with MANIFEST.open(encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if not line or line.startswith("#"):
                continue
            parts = line.split("\t")
            if len(parts) < 2:
                continue
            category, name = parts[0], parts[1].strip()
            if not name.startswith(ALLOWED_PREFIXES):
                continue
            entries.add((category, name))
    entries = sorted(entries, key=lambda item: (item[1], item[0]))

    enum_lines: list[str] = []
    name_lines: list[str] = []
    opcode = 1
    for _category, name in entries:
        enum_lines.append(f"    {sanitize_name(name)} = {opcode},")
        name_lines.append(f'    "{name}",')
        opcode += 1

    header = (
        "// MobileGL - MobileGL/MG_Protocol/generated_opcodes.h\n"
        "// Copyright (c) 2025-2026 MobileGL-Dev\n"
        "// Licensed under the GNU Lesser General Public License v3.0:\n"
        "//   https://www.gnu.org/licenses/gpl-3.0.txt\n"
        "//   https://www.gnu.org/licenses/lgpl-3.0.txt\n"
        "// SPDX-License-Identifier: LGPL-3.0-only\n"
        "// End of Source File Header\n\n"
        "#pragma once\n\n"
        "#include <cstdint>\n\n"
        "// GENERATED by scripts/generate_opcode_table.py from api_manifest.txt.\n"
        "// Opcodes are stable: names are never reordered once published.\n\n"
        "namespace MobileGL::Protocol {\n\n"
        f"inline constexpr uint32_t kMobileGLOpcodeCount = {len(entries)}u;\n\n"
        "enum class MobileGLOpcode : uint32_t {\n"
        + "\n".join(enum_lines) +
        "\n};\n\n"
        "inline constexpr const char* kMobileGLOpcodeNames[kMobileGLOpcodeCount] = {\n"
        + "\n".join(name_lines) +
        "\n};\n\n"
        "inline const char* MobileGLOpcodeName(MobileGLOpcode opcode) {\n"
        "    const auto value = static_cast<uint32_t>(opcode);\n"
        "    if (value == 0 || value > kMobileGLOpcodeCount) return \"?\";\n"
        "    return kMobileGLOpcodeNames[value - 1];\n"
        "}\n\n"
        "} // namespace MobileGL::Protocol\n\n"
        "// End of File\n"
    )
    OUTPUT.write_text(header, encoding="utf-8")
    print(f"Wrote {len(entries)} opcodes to {OUTPUT.relative_to(REPO_ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
